### ISSUE TITLE
Ctrl-d/u scrolling behavior is not consitent.

### ISSUE THREAD

**Issue by amosbird** [5digits/dactyl#106]
There are many sites which `Ctrl-d/u` scrolling is behaving funny. Take github.com as a example:
![t0 llup 0b4k7 v cx7hm](https://cloud.githubusercontent.com/assets/5085485/11452095/9821dbae-9616-11e5-914b-9ee6aa756b25.png)
![sm k0bc9pz9_ sgnccsg og](https://cloud.githubusercontent.com/assets/5085485/11452096/99bfb92c-9616-11e5-84a0-7b4f8e3a5b40.png)
![d47fht ciw k_d9rmr 12gd](https://cloud.githubusercontent.com/assets/5085485/11452097/9b282628-9616-11e5-81a7-3a35631d1929.png)

Until this frame gets scrolled to bottom, `Ctrl-d` starts to scroll the page.

**Comment by polyzen** [comment]
@amosbird, is this resolved? If so, please close.
