### ISSUE TITLE
Pendatactyl ReferenceError on Firefox 44.0a2

### ISSUE THREAD

**Issue by veeven** [5digits/dactyl#108]
Pentadactyl throwing the following error on the console on Firefox 44.0a2. And, pentadactyl commands do not work.

![pentadactyl-1 2pre 20151206_error-on-firefox44 0a2](https://cloud.githubusercontent.com/assets/6792988/11656585/33dccfb4-9ddc-11e5-8952-5e48770e522a.png)

I think the error is due to [Breaking changes in let and const in Firefox Nightly 44](https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44/).

**Comment by veeven** [comment]
Here is the text from console:
```
pentadactyl: [Begin base]
pentadactyl: Loading base: ReferenceError: can't access lexical declaration `Iter' before initialization

pentadactyl: bootstrap: ReferenceError: can't access lexical declaration `Iter' before initialization
Class@resource://dactyl/bootstrap.jsm -> resource://dactyl/base.jsm:909:1
@resource://dactyl/bootstrap.jsm -> resource://dactyl/base.jsm:1271:17
loadSubScript@resource://dactyl/bootstrap.jsm:26:12
```

**Comment by willsALMANJ** [comment]
I didn't test them individually but either bc9eb79fb310dac1ea8dd304bac4db996c51e6d8 or 65725c95164c6da1fe5bedbeafa651c06d08b72e fixed this issue.

**Comment by veeven** [comment]
The ReferenceError is no longer thrown with latest code.
