### ISSUE TITLE
Redundant linebreaks in Insert mode (when using Jupyter Notebooks)

### ISSUE THREAD

**Issue by SuperFluffy** [5digits/dactyl#109]
I am editing a Jupyter / IPython notebook, and it seems that when hitting the Return key in `Insert` mode, Pentadactyl inserts redundant linebreaks. This, however, does not happen when editing in `Pass-Through` mode (`C-z`). For example, the first case would look like:

````
foo

bar
````

While in `Pass-Through` mode the result is (as it should be):
````
foo
bar
````

Any idea what might be going on in `Insert` mode compared to `Pass-Through` mode and how I could fix this?

**Comment by ffledgling** [comment]
I've noticed this happens on a few front-end JS heavy websites (facebook.com, messenger.com are notable ones I've noticed this problem with), it's likely because of the way pentadactyl and the JS for that particular website end up interacting and not something that's wrong with penta in particular.

**Comment by prikhi** [comment]
`shift+enter` usually works as well

**Comment by denius** [comment]
It's a bug with very long history: http://code.google.com/p/dactyl/issues/detail?id=616
The temporary solution:
```
:set pk+=.*:<CR>
```

**Comment by SuperFluffy** [comment]
Some recent update fixed this, it seems. Not sure which one. Maybe 4904fb5bff72e0d45fea353372ccf9c3061722f8 ?
