### ISSUE TITLE
Pentadactyl doesn't work with Firefox 43

### ISSUE THREAD

**Issue by mrschyte** [5digits/dactyl#112]
I've tried changing the maxVersion in the install.rdf file to no avail. The plugin is installed and enabled, but it doesn't seem to start.

**Comment by petercombs** [comment]
I was having this issue as well, but I pulled the latest version, updated the install.rdf, and that seems to have fixed it for me. Are you working off commit e3c37485?

**Comment by mrschyte** [comment]
I've tried with the latest nightly; I'll check out the last commit from this repo.
