### ISSUE TITLE
recent changes cause keyboard shortcut not working on github

### ISSUE THREAD

**Issue by hrzhu** [5digits/dactyl#118]
steps to reproduce:
go to https://github.com/5digits/dactyl, type o, nothing happens, O  works. I don't know which specific commit introduce this but reverting to a19a865 the problem is gone.

**Comment by prmtl** [comment]
+1 here. On the newest build keys like 't', 'o' do not work on Github. They also do not work on Google as search input is always having focus.

**Comment by jonlorusso** [comment]
+1  

Not sure if this is related or a separate issue:
type 't' (for :tabnew), try typing 'j'. does not work. Capital J does work however.  Very odd.

Also, in slack (for instance), <Escape> does not exit -- INSERT -- mode. Again, not sure if this is related or a fully separate issue.

**Comment by Eisfreak7** [comment]
Same problem with reddit (with Reddit Enhancement Suite)
Probably because reddit and github define their own keyboard shortcuts and pentadactyl doesn't intercept them correctly.

**Comment by rbtwrrr** [comment]
@jonlorusso you have a binding for jj -> escape, right? #116

**Comment by jonlorusso** [comment]
@rbtwrrr 
`cmap jk <Escape>`

**Comment by jbylsma** [comment]
I believe these issues are all from some PassThrough changes in 28fe4af. I created a pull request #124 that I think should fix it. Can you please test?

**Comment by wasamasa** [comment]
@jbylsma Thanks, your changes fixed it for me.

**Comment by jbylsma** [comment]
This was fixed with 4904fb5 and can be closed.
