### ISSUE TITLE
Passthrough is too eager since "Improve the efficiency/bugginess of abbrev mappings."

### ISSUE THREAD

**Issue by woutershep** [5digits/dactyl#121]
On http://slashdot.org a lot of keys don't work in command mode and are instead passed through to the page. I've bisected it to:

28fe4afc4ea21d154aa4066a12cc92952e480e48 is the first bad commit
commit 28fe4afc4ea21d154aa4066a12cc92952e480e48
Author: Kris Maglione <maglione.k@gmail.com>
Date:   Sun Dec 20 20:35:23 2015 -0800

    Improve the efficiency/bugginess of abbrev mappings.

The most easy to test is the 'd' key, which instead of closing the window as expected, ends up collapsing the news items instead.

Possibly related bugs are #118 and #119

Oh and if it matters ive been using firefox 43.0

**Comment by jbylsma** [comment]
I tracked down the same commit and created PR #124 that I think fixes it. I'm pretty sure #118 and #119 are the same issue. Can you please test?

**Comment by woutershep** [comment]
Fixed by https://github.com/5digits/dactyl/commit/4904fb5bff72e0d45fea353372ccf9c3061722f8
