### ISSUE TITLE
Add-on signing in Firefox 43

### ISSUE THREAD

**Issue by vimdude** [5digits/dactyl#129]
More info on https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

How to get around this?

**Comment by vimdude** [comment]
You can override the setting to enforce the add-on signing requirement by changing the preference xpinstall.signatures.required to false in the Firefox Configuration Editor (about:config page).

**Comment by daGrevis** [comment]
Be aware that this will only work with Firefox 43.

**Comment by vimdude** [comment]
Thanks for letting me know. How will this work in the future?

**Comment by daGrevis** [comment]
https://github.com/5digits/dactyl/issues/99

**Comment by nschley** [comment]
Folks,

How does one install the willsALMANJ/pentadactyl-signed XPIs in FF44.0.2?
To install a January vintage XPI, I set
"xpinstall.signatures.required;false".
Now, FF greets my every attempt to install Will's latest signed XPI with:

> FF has blocked this site from asking if you want to install SW on your
computer.


No luck on anything:
I saw someone's post that the "sigs req'd" setting wasn't going to work in
FF44, so I tried restoring it to true.
I config'd "xpinstall.whitelist.add" with Will's github URL (
https://github.com/willsALMANJ/pentadactyl-signed)
I added Will's URL to "xpinstall.signatures.devInfoURL" (both ","- & ";"
separated, with his URL before & after the default Mozilla value.
I set "xpinstall.whitelist.required" to false.

Can anyone tell me what I need to do?
FWIW, I'm on a Mac.   Hopefully that isn't a factor!



Thanks,

Nate

2016-01-13 10:04 GMT-05:00 Raitis Stengrevics <notifications@github.com>:

**Comment by nschley** [comment]
Never mind on my last post.
I found that the setting "xpinstall.customConfirmationUI" had been set to
false.  (Why & when, I don't know.)
Restoring it to it's *default* "true" gave me the prompt to ask if I wanted
to install Will's good work.

Thanks,

Nate

2016-02-18 13:05 GMT-05:00 Nate Schley <nate.schley@gmail.com>:
