### ISSUE TITLE
Everything opens in a new tab

### ISSUE THREAD

**Issue by willsALMANJ** [5digits/dactyl#131]
Currently (as of https://github.com/5digits/dactyl/commit/b9849df56532a9fcbf2d46dfca7ea4eabc38160a), everything that opens a url opens it in a new tab. Even trying to navigate backwards causes a new tab to be opened.

**Comment by krompus** [comment]
(I don't have anything constructive to say; I just wanted to mention that I find this [humorous](https://i.imgur.com/yiOf7Xs.png). :P )

**Comment by willsALMANJ** [comment]
Hmm, I'm glad to know I'm not the only one with this issue. I just tried restarting/rehashing/cleaning things out and now I'm not seeing this behavior, so I guess it must be triggered by a command I used. I will look out for it when it happens again.

**Comment by laMudri** [comment]
I'm seeing the same on the first use after updating. Any idea what you did to fix it? Even commands like `:open` and `:winopen` open a new tab.

**Comment by laMudri** [comment]
Huh, just rebooting seems to fix it.

**Comment by willsALMANJ** [comment]
I haven't seen it again since I opened the issue and I have restarted Firefox several times. Perhaps it is related to some property set at runtime that Pentadactyl didn't clean up when it was uninstalled as part of an update.

**Comment by polyzen** [comment]
@willsALMANJ, mind closing this?

**Comment by willsALMANJ** [comment]
No problem, though closing runs counter to the devs' style even dating back to the previous issue tracker on Google Code.

**Comment by polyzen** [comment]
Hopefully Github's issue tracker is easy enough to use -- searches include closed issues, etc. -- that it won't be a problem. :p

**Comment by krompus** [comment]
I <3 Github's issue tracker. :)

I have a love/hate relationship with the email updates though, haha (I realise I can turn them off, but I haven't found any Android Github clients I like, haha).

**Comment by polyzen** [comment]
@krompus, this made things much better https://ptpb.pw/Urmp.png

**Comment by krompus** [comment]
Haha, I know, I've just not found a good Github Android app, and I actually like getting notifications on my phone when people comment on threads I'm watching. :)

I'll do some more fiddling, I suppose.

**Comment by polyzen** [comment]
I find myself jumping between mobile and desktop view pretty often. :p
