### ISSUE TITLE
disable site-specific hotkeys (e.g. on Github)

### ISSUE THREAD

**Issue by holtzermann17** [5digits/dactyl#139]
Someone has already asked about this on Superuser.com: http://superuser.com/questions/640715/how-do-i-prevent-a-page-from-hijacking-my-pentadactyl-navigation-keys but the answers there are not satisfactory.  The question (or feature request) is: 

Is there a way to make sure that no keypresses are passed through to the underlying site, except when editing text boxes?  An example site with hotkeys that cannot be disabled is (unfortunately) Github.  So issuing commands like <kbd>s</kbd> will activate Github's hotkeys not Pentadactyl's.

**Comment by jbylsma** [comment]
Your issue resembles #118, which dealt with broken Passthrough handling. It was resolved in early January. Are you using the most recent version of Pentadactyl?

I'm using Firefox 44.0.1 with the latest Pentadactyl head, and I can confirm that the Github "s" binding only works when I'm in passthrough mode.

**Comment by holtzermann17** [comment]
That is related.  I updated to what I think is the latest version of Pentadactyl [Pentadactyl 1.2pre (created 2016/01/08 18:36:26]; I am still on Firefox 43.0.  If I visit https://github.com/5digits/dactyl and press "y" to copy the URL, the URL gets copied but the browser also gets pointed to https://github.com/5digits/dactyl/tree/cf68a387394c1de27f81cd37d5d7c7525892ff12 which isn't desirable.

**Comment by holtzermann17** [comment]
https://news.google.com/ is another offender.  "o" doesn't work on this site, or is passed through to "open" a news item.

**Comment by holtzermann17** [comment]
I can confirm this is fixed with latest FF 45.0 and latest Pentadactyl.  Thanks @jbylsma.  Closing.
