### ISSUE TITLE
'incompatible with 44.0.{1,2}'

### ISSUE THREAD

**Issue by FLHerne** [5digits/dactyl#141]
When using Firefox 44.0.1 or 44.0.2, Pentadactyl gets disabled. There are no problems with 44.0 itself.

Are there really addon-breaking changes in a minor upgrade, or is this merely an issue with version-detection?

**Comment by 0x01f7** [comment]
The latest commit 0b835e1 works fine to me. (I am using Firefox 44.0.2)

**Comment by FLHerne** [comment]
Works for me too. I thought I'd already tried it, must have forgotten to actually load the new version in Firefox.
