### ISSUE TITLE
Key bindings are overridden by websites

### ISSUE THREAD

**Issue by Unode** [5digits/dactyl#147]
Some websites (including github) make heavy usage of key shortcuts.
These shortcuts somehow manage to override the default behavior of pentadactly even when not in passthrough mode nor when no `passkeys` are set for the website.

For instance on github, pressing `t` when browsing code activates the `file finder`.
The textarea field where I'm writing this text is also affected. In the past it was possible to hit `Ctrl + i` to start an external editor (usually gvim), now it simply formats the text to _italic_.

**Comment by kesava-wow** [comment]
I haven't had this problem for a while, re #139. Which commit and version of firefox are you on?

**Comment by Unode** [comment]
Hum, I just realized I can't reproduce it on this computer. I'll try updating pentadactly later. It might indeed just be the case that the version I have is old.

Kind of hard to track since we are living on nightlies these days...

**Comment by polyzen** [comment]
#139

**Comment by Unode** [comment]
Yup, false alarm. Just tested after updating. Problem is gone.
