### ISSUE TITLE
question: Is there a way to move tab to left/right under pentadactyl ?

### ISSUE THREAD

**Issue by gaohaoliang** [5digits/dactyl#15]
I find this page [Keyboard shortcuts - Perform common Firefox tasks quickly](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly), and it says `Move Tab in focus Left 	'Ctrl + Shift + Page Up'`.
I looked up the pentatactyl's manual, but I did not find it.

**Comment by osleg** [comment]
I think :tabmove command is what you looking for

**Comment by gaohaoliang** [comment]
Thanks, osleg!
