### ISSUE TITLE
can't search keyword by :s or :o after upgrading to Firefox 46

### ISSUE THREAD

**Issue by hrzhu** [5digits/dactyl#152]
The following error message printed:
     
    resource://dactyl/util.jsm: 1583: TypeError: can't assign to properties of (new String(" ")): not an object

**Comment by mario-grgic** [comment]
This is fixed in pull request https://github.com/5digits/dactyl/pull/151 so if you are building pentadactyl yourself you can merge that in manually. 

But after you fix that you run into further issues with following links (backspace does not work and you get more errors of similar kind).

**Comment by hrzhu** [comment]
Fixed in git master. This can be closed.
