### ISSUE TITLE
:tabopen does not work with Firefox 46

### ISSUE THREAD

**Issue by thisfred** [5digits/dactyl#153]
When I type

`:tabopen some string`

I get the following error:

```
resource://dactyl/util.jsm: 1583: TypeError: can't assign to properties of (new String(" ")): not an object
```

and nothing else happens.

**Comment by thisfred** [comment]
When I pass a url, it does seem to work.

**Comment by thisfred** [comment]
But previously, any other string would result in a google search for that string, rather than a javascript error.

**Comment by polyzen** [comment]
This also seems to occur with url's lacking the scheme (eg. https://).

**Comment by mariusor** [comment]
This gets fixed by https://github.com/5digits/dactyl/pull/151

**Comment by krompus** [comment]
Good to know #151 fixes it.

I tried updating to the latest nightly, and it tells me that it's incompatible. Any idea if there's a workaround for this? I remember toggling a value in about:config for previous versions to allow "incompatible" extensions to install anyways, perhaps they've changed the method?

**Comment by polyzen** [comment]
@thisfred, the fix is in master, this can be closed. :)

**Comment by thisfred** [comment]
sorry, closed now :)
