### ISSUE TITLE
Error following hints in Firefox 46

### ISSUE THREAD

**Issue by ritashugisha** [5digits/dactyl#154]
Getting the following error in Firefox 46.

`resource://dactyl/styles.jsm: 248: TypeError: can't assign to properties of (new String("hint-positions")): not an object`

Error occurs when trying to follow any link using hints.

Is this a problem related to #152 ?

**Comment by jak3** [comment]
I don't think so. The pull request [#151](https://github.com/5digits/dactyl/pull/151) does not fix this problem. I'm working on try to figure how to fix it.

**Comment by ritashugisha** [comment]
Fixed via #156. Thanks for the quick fix.
