### ISSUE TITLE
Support to LightfFirefox

### ISSUE THREAD

**Issue by arkhan** [5digits/dactyl#165]
Hello,

It's possible to add support to:

https://sourceforge.net/projects/lightfirefox/

Thanks

**Comment by tokiclover** [comment]
Is there really a need to support this? I mean there are only two releases in 2014, and nothing else? Why bother with an orphaned and one shot release?

**Comment by tokiclover** [comment]
My bad, after searching in the intertubes; it looks like a custom build than anything else. So reporting the errors when trying to load the addon won't hurt...
