### ISSUE TITLE
Disable only SOME Pentadactyl keys per site

### ISSUE THREAD

**Issue by for-coursera** [5digits/dactyl#186]
(Switching from Vimperator now; please, excuse me if I'm missing something)

Is it possible to disable only some of Pentadactyl keys on a site basis? Or, vice versa, disable all (like this `:autocmd LocationChange 'https://mail.google.com/*' :normal! <C-z>`), and then enable some?

To put that into context, I'd like, of course, to use Gmail's keys, but I'd also like to be able to open new tabs with `t`, while being in Gmail's tab.

In Vimpertor, there was `ignored-keys` file in `~/.vimperator/[profile-name]/info` folder, with a structure like the following:

    {"mail\\.google\\.com":["t","o",...]}

which literally allowed to use only listed keys on these listed websites (like, `t` and `o` on `mail.google.com`. Is there a similar solution for a Pentadactyl?

**Comment by maturano** [comment]
Try with `:help passkeys`. From there:

```
:set passkeys+=mail.google.com:jk<CR>,gi
```

**Comment by for-coursera** [comment]
Thanks! And sorry for my ignorance :(

**Comment by for-coursera** [comment]
``
