### ISSUE TITLE
[macOS] Is there any way to toggle Pentadactyl's address bar and status bar?

### ISSUE THREAD

**Issue by for-coursera** [5digits/dactyl#189]
To illustrate my question, here are two screenshots of Vimperator with the address and status bars [hidden](http://i.imgur.com/oD89Iep.png) and [shown](http://i.imgur.com/jbsEaIV.png).

With Vimperator, I have these two snippets in my rc file (taken from somewhere but they seem to do the job):

    js <<EOF
    function toggle_navbar() {
        var nb = document.getElementById('nav-bar');
        if (!nb)
            return;
        nb.style.visibility = (nb.style.visibility == '') ? 'collapse' : '';
        nb.style.overflow = (nb.style.height == '') ? '' : 'hidden';
        }
    toggle_navbar();
    EOF
    js <<EOF
    function toggle_statbar(p) {
        var bb = document.getElementById('liberator-bottombar');
        if (!bb)
            return;
        if (p == 'on'){
            bb.style.height = '';
            bb.style.overflow = '';
            return;
        }
        if (p == 'off'){
            bb.style.height = '0px';
            bb.style.overflow = 'hidden';
            return;
        }
        bb.style.height = (bb.style.height == '') ? '0px' : '';
        bb.style.overflow = (bb.style.height == '') ? '' : 'hidden';
    }
    toggle_statbar();
    EOF

But unfrtunately these two fail with Pentadactyl. Thus, I'd be grateful for any workaround here if possible :).

**Comment by maturano** [comment]
From your screenshots, I think you can archive that with: `:set go!=T`. You can see `:help guioptions` for more information.

**Comment by for-coursera** [comment]
Yep, that seems to do the trick. Strangely, I recall trying `:set go+=T` with no effect.

Anyway, thanks once again, @maturano!

**Comment by for-coursera** [comment]
Yep, that seems to do the trick. Strangely, I recall trying `:set go+=T` with no effect.

Anyway, thanks once again, @maturano!
