### ISSUE TITLE
Pentadactyl + JavaScript: getting value of an object?

### ISSUE THREAD

**Issue by for-coursera** [5digits/dactyl#196]
### Version:

```
Pentadactyl hg7290 (created 2016/07/19 07:00:08) running on:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:45.0) Gecko/20100101 Firefox/45.0
```
Firefox.app in question is actually Firefox Extended Support Release, which still [seems](https://www.mozilla.org/en-US/firefox/organizations/faq/) to [be](https://www.mozilla.org/media/img/firefox/organizations/release-overview-high-res.d18fa90b7aad.png) the latest Firefox available.

### Issue:

Let's say I open a random issue page on a GitHub tracker (like [this one](https://github.com/5digits/dactyl/issues/195)), then I open Console in Firefox and run something like this:

    alert(document.getElementsByClassName("js-issue-title")["0"]["firstChild"].textContent)

As a result, it pops me up with the title of an issue (speaking of this [particular issue](https://github.com/5digits/dactyl/issues/195), it [would be](http://i.imgur.com/BVhUv09.png) `How to achieve Ctrl-t functionality`).

Now, I want to use that value in a script with Pentadactyl. Thus, I add something like this to my `.pentadactylrc`

    :javascript <<EOF
    function dummyFu() {
        var myElement = document.getElementsByClassName("question-hyperlink");
        alert(myElement["0"].firstChild.textContent);
    }
    EOF
    map -silent <F5> -js dummyFu()

However, when run, it just says `TypeError: myElement[0] is undefined`.

I'm do not know much of JavaScript, unfortunately, so there's probably some mistake in my thinking?  I just want to be able to get an element from a page by a class and then use it my script... Would be grateful for any suggestion, thanks.

**Comment by dkearns** [comment]
See https://developer.mozilla.org/en-US/docs/Web/API/Window/content
