### ISSUE TITLE
Pentadactyl vs Waterfox

### ISSUE THREAD

**Issue by for-coursera** [5digits/dactyl#211]
[Waterfox](https://en.wikipedia.org/wiki/Waterfox) is an open-source web browser based on Mozilla Firefox for 64-bit Windows, macOS and Linux systems. What is important for us, Pentadactyl users, it's that Waterfox team [plans](https://www.reddit.com/r/waterfox/comments/6cqmhu/are_there_any_features_youd_like_to_see_in/dhz621w/) to continue supporting XUL.

However, as of current version, Pentadactyl  doesn't seem to function properly with the latest Waterfox 54.0: it installs fine (I used this [signed version](https://github.com/willsALMANJ/pentadactyl-signed)) but then just nothing happens. Same version, however, is working perfectly with Firefox ESR 45.9.0.

Any ideas?

**Comment by jjzz** [comment]
solved in #209 #210

**Comment by for-coursera** [comment]
Thanks, that seems to work!
