### ISSUE TITLE
defsearch keeps getting reset to google?

### ISSUE THREAD

**Issue by JohnnyCashout** [5digits/dactyl#212]
I have duckduckgo set as preferred search engine in firefox preferences, and I  :set defsearch=duckduckgo 

it works fine for a while, maybe a day.  then when I start firefox again, defsearch has been reset to Google again.   How can I make this setting stick?

**Comment by iegorka** [comment]
Hi,

You can save your configuration with this command:

`:mkp[entadactylrc][!] [file]`
  
            Write current key mappings and changed options to [file]. If no
            [file] is specified then ~/.pentadactylrc is written unless this file
            already exists. The special version :mkpentadactylrc! will overwrite
            [file] if it exists.

**Comment by JohnnyCashout** [comment]
thanks
