### ISSUE TITLE
Pentadactyl does not work in Firefox 54.0.1

### ISSUE THREAD

**Issue by EwaKowalczuk** [5digits/dactyl#214]
I used new installation of Firefox 54.0.1 on Debian Stretch. I compiled newest version from dactyl repository (as of 01.07.2017) and self-signed it. The .xpi file installed successfully but Pentadactyl features are no activated (I cannot issue any Pentadactyl commands). The Firefox log looks like this:

    dactyl: bootstrap: startup startup
    dactyl: bootstrap: init myemail
    ewa: bootstrap: init
    ewa: [Begin base]
    ewa: Loading base: TypeError: /^function .*?\((.*?)\)/.exec(...) is null
    
    ewa: bootstrap: TypeError: /^function .*?\((.*?)\)/.exec(...) is null
    Class@resource://dactyl/bootstrap.jsm -> resource://dactyl/base.jsm:927:1
    @resource://dactyl/bootstrap.jsm -> resource://dactyl/base.jsm:1817:12
    loadSubScript@resource://dactyl/bootstrap.jsm:26:12
    _load@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/freyja/.mozilla/firefox/2n4je0ib.default/extensions/myemail.xpi!/bootstrap.js:150:17
    load@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/freyja/.mozilla/firefox/2n4je0ib.default/extensions/myemail.xpi!/bootstrap.js:173:17
    init@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/freyja/.mozilla/firefox/2n4je0ib.default/extensions/myemail.xpi!/bootstrap.js:286:25
    startup@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/freyja/.mozilla/firefox/2n4je0ib.default/extensions/myemail.xpi!/bootstrap.js:394:13
    callBootstrapMethod@resource://gre/modules/addons/XPIProvider.jsm:4982:11
    startup@resource://gre/modules/addons/XPIProvider.jsm:2881:13
    callProvider@resource://gre/modules/AddonManager.jsm:272:12
    _startProvider@resource://gre/modules/AddonManager.jsm:759:5
    startup@resource://gre/modules/AddonManager.jsm:941:9
    startup@resource://gre/modules/AddonManager.jsm:3145:5
    observe@resource://gre/components/addonManager.js:65:9
    
    
    ewa: bootstrap: TypeError: /^function .*?\((.*?)\)/.exec(...) is null
    Class@resource://dactyl/bootstrap.jsm -> resource://dactyl/base.jsm:927:1
    @resource://dactyl/bootstrap.jsm -> resource://dactyl/base.jsm:1817:12
    loadSubScript@resource://dactyl/bootstrap.jsm:26:12
    _load@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/freyja/.mozilla/firefox/2n4je0ib.default/extensions/myemail.xpi!/bootstrap.js:150:17
    load@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/freyja/.mozilla/firefox/2n4je0ib.default/extensions/myemail.xpi!/bootstrap.js:173:17
    init@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/freyja/.mozilla/firefox/2n4je0ib.default/extensions/myemail.xpi!/bootstrap.js:286:25
    startup@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/freyja/.mozilla/firefox/2n4je0ib.default/extensions/myemail.xpi!/bootstrap.js:394:13
    callBootstrapMethod@resource://gre/modules/addons/XPIProvider.jsm:4982:11
    startup@resource://gre/modules/addons/XPIProvider.jsm:2881:13
    callProvider@resource://gre/modules/AddonManager.jsm:272:12
    _startProvider@resource://gre/modules/AddonManager.jsm:759:5
    startup@resource://gre/modules/AddonManager.jsm:941:9
    startup@resource://gre/modules/AddonManager.jsm:3145:5
    observe@resource://gre/components/addonManager.js:65:9

I'm happy to provide additional details but I'm not sure what might be important.

**Comment by iegorka** [comment]
You can find fix here #209

**Comment by EwaKowalczuk** [comment]
Thanks, I must have missed that issue. Sorry for the duplicate, I'm closing this one.
