### ISSUE TITLE
Coursera only audio on video player

### ISSUE THREAD

**Issue by achitu** [5digits/dactyl#24]
With pentadactyl enabled, the videos on coursera (for example the video on this page https://www.coursera.org/course/humanlanguage) are not working, only audio is enabled, but no video part. With pentadactyl disabled (no restart needed after disabling) videos are working as expected (video and audio).

**Comment by dkns** [comment]
Are you sure this isn't something related to your setup? I can play video on that page just fine. 

    Pentadactyl hg7166 (created 2015/03/24 07:00:04) running on:
    Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by achitu** [comment]
Sorry for the late reply. I'm testing it now with Iceweasel 42, and everything is okay. I will close this issue.
