### ISSUE TITLE
Some Firefox popup menus don't work when the location bar is hidden

### ISSUE THREAD

**Issue by maki57** [5digits/dactyl#28]
When clicking some buttons of Firefox's menus or extensions placed on any of the toolbars, their menus don't pop up when the location bar is hidden with `:se guioptions-=T`. Here are some examples of Firefox menus and extensions on either the tabs bar (top) or on the bookmarks toolbar (bottom) for instances where they work or don't work with or without the location bar:

#### Firefox Menus
**Downloads w/ Location Bar**
![downloads-bar](https://cloud.githubusercontent.com/assets/11873511/7071059/776cf2c6-df15-11e4-8aac-6a4668785afa.png)
Works

**Downloads w/o Location Bar**
![downloads-nobar](https://cloud.githubusercontent.com/assets/11873511/7071064/7e3da1c2-df15-11e4-803f-cb78ea793bb2.png)
Works

**Developer Tools w/ Location Bar**
![devtools-bar](https://cloud.githubusercontent.com/assets/11873511/7070983/0520f3a2-df15-11e4-8ce1-e34bf097a7c3.png)
Works

**Developer Tools w/o Location Bar**
![devtools-nobar](https://cloud.githubusercontent.com/assets/11873511/7071018/4354095c-df15-11e4-94b0-07da1cc9d389.png)
Doesn't Work

#### Extensions
**Privacy Badger w/ Location Bar**
![privacy badger-bar](https://cloud.githubusercontent.com/assets/11873511/7071070/8224cf7c-df15-11e4-9053-71fac5b00fbe.png)
Works

**Privacy Badger w/o Location Bar**
![privacy badger-nobar](https://cloud.githubusercontent.com/assets/11873511/7071081/99717464-df15-11e4-8b7f-e869e7dde6ce.png)
Works

**uBlock w/ Location Bar**
![ublock-bar](https://cloud.githubusercontent.com/assets/11873511/7071082/99751416-df15-11e4-92eb-d63de866846c.png)
Works

**uBlock w/o Location Bar**
![ublock-nobar](https://cloud.githubusercontent.com/assets/11873511/7071085/9e0d00c4-df15-11e4-9f58-818dd31d3058.png)
Doesn't Work

Using `:se guioptions+=T` to bring back the location bar allows the menus to work, so there's no need to disable Pentadactyl.

There was an issue mentioning this in uBlock's GitHub page, but it's been removed (I think it was because it didn't belong there).

**Comment by WyohKnott** [comment]
Full explanation here:
https://github.com/gorhill/uBlock/issues/112#issuecomment-96356864

**Comment by zarelit** [comment]
Same here using pentadactyl commit 48acf656ec9cd

**Comment by stef** [comment]
just a note: the solution^Wworkaround is to put into your .pentadactylrc the following line:
style -name ublick * #nav-bar * { visibility: visible; }

src: https://github.com/gorhill/uBlock/issues/112#issuecomment-95848638

**Comment by maki57** [comment]
That fixed it.
