### ISSUE TITLE
Custom extended hints mode

### ISSUE THREAD

**Issue by Eisfreak7** [5digits/dactyl#30]
Hi
I just recently switched to pentadactyl and it solves most of the limitations I had with vimperator.
One annoyance remains, however (that I didn't manage to solve):
Is there the possibility to create custom hint actions? The default one is "open", ";" allows for different ones, but is there a way to define a new one?
The uses I have in mind are:
- I have a "mpv" command that opens the current page with the mpv video player (I use this for youtube videos). I'd like to be able to open links directly in mpv without having to load the link first.
- I would like being able to save links to pocket without opening them (although I would have to figure out how to save links to pocket through pentadacyl at all, currently I am using the default hotkey the pocket addon offers)

Am I missing a feature or is this just not possible?

**Comment by hdhoang** [comment]
you can add new extended hints for `;` with
```
javascript <<EOS
hints.addMode("k", "prompt", function)
EOS
```
There are several example pentadactylrc gists with such commands. The second argument to the function would be the hint's location, see https://github.com/5digits/dactyl/blob/174b8ae0b67b501509494ba4462c077010955915/common/content/hints.js#L790

I was in a similar situation with pocket, and have found a relevant function at https://dxr.mozilla.org/mozilla-central/source/browser/components/pocket/pktApi.js#319. But now I have switched to wallabag, which just uses a simple GET to add an url.

**Comment by Eisfreak7** [comment]
Thanks, I already gave up hope but this is exactly what I needed.
For the record, if anybody finds this on his quest to add a mpv extended hint:
```
javascript <<EOS
hints.addMode("m", "prompt", (elem, loc) => dactyl.execute("!mpv '" + loc + "' &", null, true));
EOS
```
You have to press escape after selecting a link, otherwise the navigation somehow doesn't work.

The pocket api also is quite helpful. I suppose this is where the integration everybody hates proves itself helpful. However, when I try
```
:javascript pktUI.tryToSaveUrl("https://github.com", "github")
```
nothing happens. Manually pressing the "pocket" button in firefox works though.

Maybe I should simply also try out wallabag before fighting the pocket api further. I intended to do it for a while now anyways.

Thanks again!

**Comment by hdhoang** [comment]
In case anyone is still looking for pocket integration, you can use `;c<hint>o` to access the "Save link to Pocket" context menu item.
