### ISSUE TITLE
String.quote is missing in Firefox 37

### ISSUE THREAD

**Issue by brookst** [5digits/dactyl#39]
My command macros recently stopped working due to the removal of String.quote in Firefox. I managed to fix the compileMacro function in the Util module but I did so by inlining the escapeString function. I'm a bit rusty with my javascript so I can't see an obvious way of reusing the escapeString function. There are also a few other locations where String.quote was used but I haven't seen them cause problems yet and I would like to know what the best replacement would be.

See this page about the removal of String.quote:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/quote

**Comment by dkearns** [comment]
As the document you linked suggests try JSON.stringify.
