### ISSUE TITLE
tab-options plugin breaks :tabclose command

### ISSUE THREAD

**Issue by lolilolicon** [5digits/dactyl#4]
I'm using Firefox 36.0.1 with Pentadactyl hg7166 (2015/03/11 nightly).
The [tab-options plugin](http://5digits.org/pentadactyl/plugins#tab-options-plugin) (-dev version) makes the :tabclose command appear to do nothing, which exactly defeats its own purpose.
This plugin is really nice. Will someone take a look, please?

**Comment by Raziel-23** [comment]
@lolilolicon: [Here](https://code.google.com/p/dactyl/issues/detail?id=1279#c3) is attached the updated tab-options plugin.
BTW. Devs are more active on [the Google Code issue tracker](https://code.google.com/p/dactyl/issues/list) than here.

**Comment by kmaglione** [comment]
We don't use this issue tracker. Please file at Google Code.

**Comment by lolilolicon** [comment]
Thank you @Raziel-23 for the link. I got the updated code from there, and it's working. However, the plugin page at 5digits.org is not updated yet. For anyone interested, the fix is:

    -            for (let val in values(options["tabclose"])) {
    +            for (let val of options["tabclose"]) {

Perhaps @5digits should create a repo for the plugins, too?
