### ISSUE TITLE
Is teledactyl stable enough for a release ?

### ISSUE THREAD

**Issue by i5513** [5digits/dactyl#42]
Hello,

I can see not commit to teledactyl from 2013. At http://5digits.org/teledactyl can be read about it is still at alpha stage.

Do you have any plan to release it ? Has it at least the same stability than muttator (released on 2013) ?

Thank you !!

**Comment by dkearns** [comment]
Unfortunately it's severely rotten at the moment.  It will probably be resurrected one day if only because @kmaglione won't let me delete it.

**Comment by dkearns** [comment]
https://blog.mozilla.org/thunderbird/2014/11/thunderbird-reorganizes-at-2014-toronto-summit/

**Comment by i5513** [comment]
Thanks for the comment and forma the link, be free of closing this issue

Regards

**Comment by polyzen** [comment]
@i5513, you can close this yourself. Please do so.

**Comment by i5513** [comment]
Ok , closing :(

**Comment by polyzen** [comment]
Sorry if that sounded rude. :p
