### ISSUE TITLE
Cosmetic errors in tab bar on OSX

### ISSUE THREAD

**Issue by krakpot** [5digits/dactyl#44]
Using the nightly build from 2015-05-12 on Firefox 37.02.2 on Mac OSX Yosemite 10.10.3 

There are som cosmetic errors in the tab bar; it does not properly line up with the top of the window and the plus sign to add a new tab has strange proportions (looks a bit squashed vertically). I do not see these issues when running on Windows.

Please see the attached image for details

![screenshot](https://cloud.githubusercontent.com/assets/1367689/7595461/84a7305a-f8e7-11e4-9936-b77a0816e872.png)

**Comment by mario-grgic** [comment]
Add the following to your .pentadactylrc

```vimrc

" customize the size of tabbar and tabs to fix the defaults defined in
" dactyl.css
:style chrome://browser/* <<EOF
    [dactyl-australis=true] :-moz-any(xul|tab.tabbrowser-tab, .tabs-newtab-button) .tab-background > * {
       min-height: 30px !important;
       max-height: 30px !important;
    }

    [dactyl-australis=true] :-moz-any(xul|tab.tabbrowser-tab, .tabs-newtab-button)
        .tab-background > :-moz-any(.tab-background-start, .tab-background-end)::after {
       background-size: 30px 30px !important;
       max-height: 30px !important;
       min-height: 30px !important;
    }

    [dactyl-australis=true] .tabbrowser-tabs {
       min-height: 33px !important;
       max-height: 33px !important;
    }
EOF
```

This looks good on OS 10.9 (Mavericks), not sure about Yosemite. You can play with the tab and tabbar height numbers (something else other than 30px and 33px respectively) if it doesn't look good as is.

**Comment by krakpot** [comment]
I added the above proposed solution to ~/.pentadactylrc and it works very good, see attached file. Thank you.

![screenshot_after](https://cloud.githubusercontent.com/assets/1367689/7688061/072eaa4e-fda2-11e4-9627-eb422ce38d68.png)

It would be great if this could be the default configuration for OSX
