### ISSUE TITLE
Unable to Hide Tab Bar

### ISSUE THREAD

**Issue by xelxebar** [5digits/dactyl#46]
## Overview

Given the available items under *guioptions* and *toolbarhide*, I expect to be
able to control the visibility of the tab bar but am un able to.

Is there another, canonical way to hide/show the tab bar?

## Environment

    :version
    Pentadactyl 1.2pre (created 2015/05/15 11:35:37) running on:
    Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by dkearns** [comment]
:help 'showtabline'
