### ISSUE TITLE
When using reviewable.io, clickling on a line to open a comment opens and the closes

### ISSUE THREAD

**Issue by tomprince** [5digits/dactyl#49]
When I try click on a line to open a new inline-comment, when using reviewable.io ([sample review](https://reviewable.io/reviews/Reviewable/demo/1), it opens a new comment, and then immediately hides it again. If I double click instead , it appears to properly open it.

https://github.com/Reviewable/Reviewable/issues/101

**Comment by polyzen** [comment]
@tomprince, is this still an issue? If not, please close this.

**Comment by tomprince** [comment]
I haven't had the opportunity to use reviewable.io or dactyl recently, so I don't know if this is still an issue.
