### ISSUE TITLE
Plugin and Colorscheme links on website broken

### ISSUE THREAD

**Issue by addisonamiri** [5digits/dactyl#54]
Both the user plugins and user colorscheme links on the [official page](http://5digits.org/pentadactyl/plugins) redirect to the github and I can't seem to find them on the github. Have they been relocated or is there somewhere else I can find them?

**Comment by Delapouite** [comment]
Yes the website would need serveral updates in regards of old links pointing to code.google and the sourceforge icon in the footer.

**Comment by addisonamiri** [comment]
Is there any way I (or someone else in the community) could help? I know it would take a lot of developer time away from the project to implement something like I mentioned in #26 but I'd love to help you guys out with the meticulous parts of this project. I'm closing this because it's clear this is a part of the bigger distribution problem for these projects. Feel free to reopen it if you want to track this separately though.
