### ISSUE TITLE
Pentadactyl nightlies are not compatible with the Firefox Developer Edition 40.0a2

### ISSUE THREAD

**Issue by deiwin** [5digits/dactyl#56]
Or at least this is the error I get when trying to install them.

Would fixing this be an issue of just marking the extension as compatible or are there any blocking issues for this?

**Comment by ianyfan** [comment]
Can you do this again for 41 please?

**Comment by ianyfan** [comment]
@dkearns Can you do this again for 41 please?

**Comment by deiwin** [comment]
+1

**Comment by dkearns** [comment]
Done.  There was an incompatibility in 41 until this week.

**Comment by deiwin** [comment]
Thanks!
