### ISSUE TITLE
Would it be possible to support Pale Moon? 

### ISSUE THREAD

**Issue by Hund** [5digits/dactyl#58]
Pale Moon is a old fork of Firefox, it's been around for ages and it uses the old UI of Firefox. I belive it counts as version 25 of Firefox? Would it be possible to support Pale Moon? 

The developer of PM released a old version of Pentadactyl that works. It works, but it would be great to not have a 1,5 year old version. :)

**Comment by dkearns** [comment]
No, unfortunately someone would need to continue developing that old version separately.
