### ISSUE TITLE
:buffer ignores tabs in other tab groups

### ISSUE THREAD

**Issue by cdosborn** [5digits/dactyl#59]
When I restart firefox, with multiple tab groups. Tabs are lazy loaded as usual, when I press `\b` tabs in other groups are not displayed until I have switched to them via control-backtick.

**Comment by kmaglione** [comment]
Panorama is not meant to be extensible. It has no API, and getting access to tab group information at all requires loading its large, slow, expensive iframe and poking into its UI code. Even at that, it doesn't initialize its group information until the first time it the user opens it.

And, in any case, the current implementation is almost certainly going to be removed from Firefox before very long. The support in `:buffer` is strictly meant to be better-than-nothing.
