### ISSUE TITLE
tag completion on bmark and bmarks command 

### ISSUE THREAD

**Issue by tjouan** [5digits/dactyl#6]
After updating to firefox 36 and rebuilding pentadactyl, I have
problems with tag completion on commands like this:

    :bmark -tags 

This won't complete nor list anything, as if I had no tag ("No
Completions" is shown below status bar). I tried removing my
~/.pentadactylrc, rebuild again the extension, but still have this
issue.

Is there something I should do or check to have it working again?

**Comment by thoms86** [comment]
Can confirm this for ff35 & ff36 (linux & windows).

`git bisect` shows the problem was introduced with commit 7ee579200f5f49748418fc06b8c37cadea609610 (*Fix all the things. And break most of the other things, in all likelihood.*)

However, I did not test this with a new/clean ff profile so far.

**Comment by thmsaurel** [comment]
I confirm this problem on MaOSX with firefox 36.

**Comment by dkearns** [comment]
Fixed by bf133a42c9b829b5e6487e3546228220d9a82af6
