### ISSUE TITLE
Status bar icon sizes

### ISSUE THREAD

**Issue by willsALMANJ** [5digits/dactyl#63]
Some status bar icons (e.g. Self-destructing Cookies) appear bigger than most (e.g. NoScript) and the height of the status bar is increased to accommodate them. I haven't looked into how the status bar is styled, but is this something can be fixed? Or is the issue that some add-ons do not provide icons with low enough resolution?

**Comment by jaseg** [comment]
I second this, this is pretty annoying. I just emailed SDC's author asking about this. I will update this issue when I get a reply.

**Comment by willsALMANJ** [comment]
For whatever reason, this issue seems to be fixed in Firefox 40.
