### ISSUE TITLE
Bookmarklets stop working in main window

### ISSUE THREAD

**Issue by polm** [5digits/dactyl#65]
This is an issue I've noticed on both Windows 7 and Linux (Arch) with Pentadactyl. In any Firefox window that's been open for a while, when using [Pintaboard](https://github.com/bnbeckwith/pintaboard) no error will occur but bookmarks will not be saved as expected. Normally I'd expect this to be a problem with Pintaboard but since the code hasn't changed in years, this only started happening maybe two months ago, and it seems to work in new windows I'm guessing it's something in Pentadactyl. 

Regarding the bit about new windows, once I notice bookmarks aren't being saved, if I open the link I want to use in a new window Pintaboard works just fine. It also works if I restart Firefox. 

Is there an existing issue that might cause this, or is there some kind of logging I can enable to investigate it more closely? I looked at the Pintaboard source (it's not terribly long or complicated) and it didn't seem to be doing anything particularly strange.

**Comment by polyzen** [comment]
@polm, is this resolved?

**Comment by polm** [comment]
Since I posted this I've stopped using Firefox, so no idea if it's fixed or not.

**Comment by polyzen** [comment]
It would probably be best if you just close this then. :) It can be re-opened if someone else runs into it.
