### ISSUE TITLE
has yankshort stopped working?

### ISSUE THREAD

**Issue by aleprovencio** [5digits/dactyl#66]
Please test yanking these urls: https://bugzil.la/488280 and https://youtu.be/TLL9aG0Tvng

**Comment by Earnestly** [comment]
Works fine here.  On commit https://github.com/5digits/dactyl/commit/f4790729da91ea76e57538e09df08673640be542

**Comment by aleprovencio** [comment]
Ops so sorry you're right, thank you @Earnestly
