### ISSUE TITLE
Autocompletion stopped working

### ISSUE THREAD

**Issue by mklishevych** [5digits/dactyl#67]
Hello guys.

Recently autocompletion stopped working for me. When I start firefox from CLI, I see a lot of below errors:

```
pentadactyl: bootstrap: SyntaxError: expected expression, got '=>'
```

Do you have any idea why this occurred and how to resolve it? Thanks.

**Comment by alexphillips** [comment]
I'm getting the same issue, guessing it's related to this FF bugfix: https://bugzil.la/1141392

**Comment by mpereira** [comment]
Same thing here, and it also seems none of my leader mappings are working.

**Comment by mpereira** [comment]
I just updated Pentadactyl to hg7218 and the autocompletion and mappings are working again.

**Comment by mklishevych** [comment]
@mpereira, yep, it works now. So I guess this can be closed.
