### ISSUE TITLE
Pentadactyl errors on completion.jsm

### ISSUE THREAD

**Issue by xificurC** [5digits/dactyl#69]
This happened to me on `HEAD` both on an Arch Linux box and a Windows 7 one. The code from [here](https://github.com/5digits/dactyl/blob/master/common/modules/completion.jsm#L141) is parsed incorrectly, an error of `expected expression, got =>` is raised. After joining the lines to

                return this.filters
                           .reduce((res, filter) => res.filter((item) => filter.call(this, item)), items);

the error goes away. Not sure if this is triggered only in some specific cases or not as a bug like this would surely be caught by now since the error happens right after starting firefox and many things don't work correctly afterwards.

Thanks for this plugin, I use it everyday and on every machine I can. Much appreciated!

**Comment by h46incon** [comment]
It is work for me with firefox 39.0 and win7. Thanks for sharing.

**Comment by rmloveland** [comment]
I also experienced the behavior described by @xificurC; the suggested fix worked for me as well.

**Comment by polyzen** [comment]
@xificurC, @h46incon, @rmloveland, is this resolved?

**Comment by xificurC** [comment]
@polyzen after a while this just started to work for me.

**Comment by polyzen** [comment]
Glad to hear that. :) If the workaround is no longer needed, please close this when you get a chance.

**Comment by xificurC** [comment]
True, forgot about that
