### ISSUE TITLE
ReferenceError: CompletionContext is not defined

### ISSUE THREAD

**Issue by Massimo-B** [5digits/dactyl#70]
Since Firefox-39.0 I have this error when trying to [o]pen an new page and searching the history. History doesn't get opened, but this error:

resource://dactyl-content/commandline.js: 1107: ReferenceError: CompletionContext is not defined

This is the latest build from hg sources.

**Comment by brendes** [comment]
Today I was having a similar problem with a previous build of Pentadactyl with a fresh download of Firefox 39.0 running Debian. I got the same error message on every keybind I tried, which broke most of them. However, I just installed a fresh build of the extension from *this* repo and the problem appears to be gone.

**Comment by Massimo-B** [comment]
I did a fresh install and it did not change anything. Some other host with same Pentadactyl but FF-38.? does not have the issue.

**Comment by brendes** [comment]
I have an OS X machine that is experiencing this problem but I have not yet taken any steps to fix the issue. Within the next day or two I'll take note of the current setup, then attempt to do the same thing I did on my Debian box.

**Comment by glittershark** [comment]
I was having this issue on Firefox 39 running on Arch Linux with a build based on the tip of the hg repository - rebuilt and installed with this repo and it's fixed.

**Comment by Massimo-B** [comment]
Thanks for the hints. How do I re-install the best way? Most times doing
```
make -C pentadactyl install
```
FF doesn't notice anything. I also tried deinstalling all Pentadactyl in FF. Then I tried doing the re-install with FF not running. Only a few times it works and the installation dialog appears.

**Comment by glittershark** [comment]
I do
```
make -C pentadactyl xpi
```
and then "install extenstion from file" from the dropdown in the upper-right of `about:addons`

**Comment by glittershark** [comment]
(the file in question goes to `downloads/` in the root of the dactyl repo

**Comment by Massimo-B** [comment]
Ok, I re-installed via File->Open File.
But the issue is still the same.

**Comment by Massimo-B** [comment]
Do you have the exact version of Firefox-39.0, as earlier versions did not have this issue?

Moreover I see some more issue when starting Firefox:
```
/home.crypt/mb/.pentadactylrc:68: E518: Unknown option: complete
Invalid argument: guioptions=Cmrs: commandline.widgets is null
```

Line 68 in the rc:
```
set complete=location,file,search
```

**Comment by setharnold** [comment]
Note that tip of hg has this trouble but tip of git fixes it. Git clone this repo, recompile, and enjoy.

**Comment by Massimo-B** [comment]
Done and fixed :) Thank you so much.
