### ISSUE TITLE
Please update dactyl pages to reflect that the project is dead

### ISSUE THREAD

**Issue by apeyser** [5digits/dactyl#77]
In fact, the dactyl pages are still pointing at the dead hg repositories from google code on top of not identifying dead parts.

**Comment by apeyser** [comment]
Hmm, when a project doesn't work with it's framework for more than a year...
You're dead...
and it's polite to not force people to search through multiple sites to id it...
and even more so to have web pages pointing to dead repos...
and not marking it sure doesn't motivate me to try to help to bring it to life...

The last major update was 2013 (to teledactyl)...
and again, if you wanted to motivate new developers, it would sure be helpful to say something more than just "invalid"...

It's too bad...

**Comment by eboth** [comment]
Pentadactyl is alive and kicking as you can see from the number of issues that have been closed recently. Bugs are corrected, and the extension is adapted to changes in new Firefox versions.

**Comment by Delapouite** [comment]
I think the point apeyser is trying to make is that yes, people involved on this issue tracker are well aware that the project is going well as you mention @eboth 

But the way new people usually get their first impression is through the public website that should be in par with the amazing work done on the code side. Unfortunately that's not the case at the moment.
