### ISSUE TITLE
Firefox 42 / Electrolysis / links broken

### ISSUE THREAD

**Issue by mmehnert** [5digits/dactyl#84]
In newer firefox versions with electrolysis activated the following of links is broken. (No link hint numbers are displayed)

**Comment by tpruzina** [comment]
this is a duplicate of existing bug

**Comment by polyzen** [comment]
@mmehnert, please close this if it is a dupe.

**Comment by mmehnert** [comment]
I guess I'll close it then. :-) #99 looks as if the topic is covered.
